#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server

if [ "$#" -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ "$#" -eq 4 ]; then
	file_path="$1"
	ip="$2"
	username="$3"
	ssh_key_path=$4
	scp -o StrictHostKeyChecking=no -i "$ssh_key_path"\
		"$file_path" "$username@$ip":~/
elif [ "$#" -eq 3 ]; then
	file_path="$1"
	ip="$2"
	username="$3"
	scp -o StrictHostKeyChecking=no "$file_path" "$username@$ip":~/
fi
