#!/usr/bin/env bash
# This script write in displays the time for 12 hours and 59 minutes

hour=0
while [ $hour -le 12 ]; do
	echo "Hour: $hour"
	hour=$((hour++))
	minute=1
	while [ $minute -lt 60 ]; do
		echo "$minute"
		minute=$((minute++))
	done
done
