#!/usr/bin/env bash
# Write a Bash script that displays the time for 12 hours and 59 minutes

hour=0
while [ $hour -lt 12 ]; do
	echo "Hour: $hour"
	((hour++))
	minute=1
	while [ $minute -lt 60 ]; do
		echo "$minute"
		((minute++))
	done
done
