#!/usr/bin/env bash
# Script that configures ufw firewall

# Install ufw
sudo apt-get update -y
sudo apt-get install ufw -y

sudo ufw disable

# Config ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

# Run configures of ufw
sudo ufw enable
